### ISSUE TITLE
Chrome android does not work anymore

### ISSUE THREAD

**Issue by zoriya** [ThaUnknown/jassub#33] opened 2023-11-06 00:23 UTC
Subtitles simply don't appear on chrome android anymore (could not tell from which version, it was already the case in 1.7.9 but maybe before too). This can be reproduced from this page, for example: https://thaunknown.github.io/jassub/jassub/simple/index.html

There aren't any errors, and debug messages in the console appears when the subtitle should be shown. It feels like everything is working as it should, but subtitles are not shown.

**Comment by ThaUnknown** [comment] 2023-11-06 00:26
![Screenshot_2023-11-06-01-25-43-905_com brave browser](https://github.com/ThaUnknown/jassub/assets/6506529/124f90a3-1494-476c-be79-7868ceef6ed6)
can't reproduce

**Comment by zoriya** [comment] 2023-11-06 00:35
Interesting, even with brave, it does not work for me.

**Comment by ThaUnknown** [comment] 2023-11-20 23:12
this is likely due to offscreen render, it's a chromium bug

**Comment by zoriya** [comment] 2023-12-12 17:14
The issue for the sandbox was #32 (which was fixed) but my codesandbox does indeed show another issue (I have not faced in production yet)

**Comment by ThaUnknown** [comment] 2023-12-12 17:19
as I said, disabling offscreen render fixes this on android, I don't know why this happens, I assume it occurs when the bitmap given to skia is too big?

**Comment by ThaUnknown** [comment] 2024-07-25 19:37
closing as no reproduction is available

**Closed by ThaUnknown** 2024-07-25 19:37 UTC
